# Generated by Django 4.2.23 on 2025-08-04 22:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_name', models.CharField(max_length=100)),
                ('onepassword_id', models.CharField(max_length=100, unique=True, verbose_name='1Password ID')),
            ],
        ),
        migrations.CreateModel(
            name='CCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe the purchase in detail.')),
                ('vendor', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.EmailField(max_length=254)),
                ('payment_code', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('credit_card_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccbot.ccname')),
            ],
        ),
    ]
