# Generated by Django 4.2.23 on 2025-08-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccname',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ccrequest',
            name='it_approval',
            field=models.BooleanField(default=False),
        ),
    ]
